### ISSUE TITLE
Refactor author model's id field

### ISSUE THREAD

**Issue by willfenton** [CMPUT404W20Project/CMPUT404-project-socialdistribution#44]
Right now the ID of the Author model is a UUID, it should be `{host}/author/{uuid}`

**Comment by um4r12** [comment]
Are you sure? We store the `host` field. If you do author.get(pk=uuid).url() you should get something like that?

**Comment by willfenton** [comment]
It seems like it, based on example_article

```
	"author": {
		"id":"http://127.0.0.1:5454/author/de305d54-75b4-431b-adb2-eb6b9e546013",
		"host":"http://127.0.0.1:5454/",
		"displayName":"Greg Johnson"
                "url":"http://127.0.0.1:5454/author/de305d54-75b4-431b-adb2-eb6b9e546013",
	},
```

ID is the same as URL here

**Comment by willfenton** [comment]
It does seem strange though

**Comment by um4r12** [comment]
I had included this in the initial setup
```
    @property
    def url(self):
        # In the future use url reverse
        # reverse('author', args=[str(id)])
        return("%s/author/%s" % (self.host, self.id))
```
But I think we will probably need to modify it, unless the API call can return this property? But I think its generated on the fly when it is called.

**Comment by willfenton** [comment]
Our ID now: `de305d54-75b4-431b-adb2-eb6b9e546013`

What our ID should be: `http://127.0.0.1:5454/author/de305d54-75b4-431b-adb2-eb6b9e546013`
